//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSBMission3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gsbrapports2021Entities : DbContext
    {
        public gsbrapports2021Entities()
            : base("name=gsbrapports2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<famille> famille { get; set; }
        public virtual DbSet<medecin> medecin { get; set; }
        public virtual DbSet<medicament> medicament { get; set; }
        public virtual DbSet<offrir> offrir { get; set; }
        public virtual DbSet<rapport> rapport { get; set; }
        public virtual DbSet<visiteur> visiteur { get; set; }
    }
}
