//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSBMission3
{
    using System;
    using System.Collections.Generic;
    
    public partial class offrir
    {
        public int idRapport { get; set; }
        public string idMedicament { get; set; }
        public Nullable<int> quantite { get; set; }
    
        public virtual medicament medicament { get; set; }
        public virtual rapport rapport { get; set; }
    }
}
